#!/bin/sh
# A C++ compiler for WSL without root.
#
# This machine's WSL has gcc but not g++ - no cc1plus, no libstdc++ headers -
# and installing one needs a password nobody is awake to type.  So do what
# make_sysroot.sh already does for the guest: fetch the Debian/Ubuntu packages
# and unpack them into a directory.  `dpkg -x` needs no privileges at all.
#
#   sh tools/get_gpp_nosudo.sh          # into ~/gpp
#   ~/gpp/bin/g++ -O2 file.cpp -o file
#
# The wrapper it writes points the system gcc at the unpacked backend and
# headers, which is all "being g++" amounts to.
set -e
PREFIX=${1:-$HOME/gpp}
MIRROR=http://archive.ubuntu.com/ubuntu/pool/main/g/gcc-11
VER=11.4.0-1ubuntu1~22.04.3

mkdir -p "$PREFIX/debs" "$PREFIX/root" "$PREFIX/bin"
cd "$PREFIX/debs"

for pkg in "g++-11_${VER}_amd64.deb" "libstdc++-11-dev_${VER}_amd64.deb"; do
    if [ ! -f "$pkg" ]; then
        echo "fetching $pkg"
        curl -sfL -O "$MIRROR/$pkg" || { echo "cannot fetch $pkg"; exit 1; }
    fi
    dpkg -x "$pkg" "$PREFIX/root"
done

GCCDIR="$PREFIX/root/usr/lib/gcc/x86_64-linux-gnu/11"
[ -x "$GCCDIR/cc1plus" ] || { echo "no cc1plus under $GCCDIR"; exit 1; }

cat > "$PREFIX/bin/g++" <<EOF
#!/bin/sh
# Generated by tools/get_gpp_nosudo.sh.  The system gcc, told where the
# unpacked C++ backend and headers live.
#
# No -x c++ here, deliberately.  It looks harmless - gcc picks C++ for a .cpp
# by extension anyway - but -x applies to *every* input that follows it,
# including object files, and gcc then reads an ELF as though it were source
# and reports a stray \\177 on line 1.  Let extensions decide; a caller who
# wants a .c compiled as C++ can say so itself.
exec gcc \\
    -B "$GCCDIR" \\
    -isystem "$PREFIX/root/usr/include/c++/11" \\
    -isystem "$PREFIX/root/usr/include/x86_64-linux-gnu/c++/11" \\
    -isystem "$PREFIX/root/usr/include/c++/11/backward" \\
    "\$@" -lstdc++ -lm
EOF
chmod +x "$PREFIX/bin/g++"

echo "== checking"
cat > "$PREFIX/hello.cpp" <<'EOF'
#include <string>
#include <vector>
#include <cstdio>
int main() {
    std::vector<std::string> v{"c++", "works"};
    std::printf("%s %s\n", v[0].c_str(), v[1].c_str());
}
EOF
"$PREFIX/bin/g++" -O2 "$PREFIX/hello.cpp" -o "$PREFIX/hello"
"$PREFIX/hello"
echo "g++ at $PREFIX/bin/g++"
