#!/bin/sh
# Builds stand-in libcudart / libcublas / libcublasLt / libcudnn / libcufft.
#
# The experiment these serve: run the *CUDA* build of voicevox_onnxruntime under
# the emulator with no GPU and no CUDA installed, and find out which of ONNX
# Runtime's 2793 registered kernels a real model actually launches.  That number
# is what decides whether "hook the CUDA calls and do the maths natively" is a
# weekend or a year.
#
# Every entry point the provider imports becomes a stub that returns success.
# A handful are real: the allocator hands out host memory, the copies are
# memcpy, and `__cudaRegisterFunction` records each kernel's name so that
# `cudaLaunchKernel` can print the one being launched.  Nothing computes
# anything - the point is the list of names, not the answer.
#
#   sh tools/make_cuda_stubs.sh <dir with libvoicevox_onnxruntime_providers_cuda.so>
#
# Run it on Linux x86-64 (WSL does).  Output goes to guest/cudastub/.
set -e
cd "$(dirname "$0")/.."
SRC=${1:-cuda/voicevox_onnxruntime-linux-x64-cuda-1.17.3/lib}
PROVIDER="$SRC/libvoicevox_onnxruntime_providers_cuda.so"
[ -f "$PROVIDER" ] || { echo "no $PROVIDER"; exit 1; }

OUT=guest/cudastub
mkdir -p "$OUT"

# Everything the provider needs, grouped by the library it expects it from.
nm -D --undefined-only "$PROVIDER" | awk '{print $2}' | grep '@lib' |
    sed 's/@GLIBC[^ ]*//' | sort -u > "$OUT/imports.txt"

for lib in libcudart.so.12 libcublas.so.12 libcublasLt.so.12 libcudnn.so.8 libcufft.so.11; do
    base=$(echo "$lib" | sed 's/\.so\..*//')
    grep "@$lib\$" "$OUT/imports.txt" | sed "s/@$lib\$//" | sort -u > "$OUT/$base.syms"
    n=$(wc -l < "$OUT/$base.syms")
    printf '%-18s %s symbols\n' "$lib" "$n"

    {
        echo "// Generated by tools/make_cuda_stubs.sh - do not edit."
        echo "// Stand-in for $lib: every entry point the CUDA provider imports,"
        echo "// answering success without doing anything."
        echo '#include "cudastub.h"'
        echo
        while read -r sym; do
            case "$sym" in
                # The ones with real behaviour live in cudastub.c.
                cudaMalloc|cudaFree|cudaMemcpy|cudaMemcpyAsync|cudaMemset|\
cudaMemsetAsync|cudaMallocHost|cudaHostAlloc|cudaFreeHost|cudaLaunchKernel|\
cudaGetDeviceCount|cudaGetDevice|cudaSetDevice|cudaGetDeviceProperties_v2|\
cudaDeviceGetAttribute|cudaRuntimeGetVersion|cudaGetErrorString|cudaGetErrorName|\
cudaStreamCreateWithFlags|cudaStreamDestroy|cudaStreamSynchronize|cudaMemGetInfo|\
cudaMemcpy2DAsync|__cudaRegisterFatBinary|__cudaRegisterFatBinaryEnd|\
__cudaRegisterFunction|__cudaRegisterVar|__cudaUnregisterFatBinary|\
__cudaPushCallConfiguration|__cudaPopCallConfiguration)
                    ;;
                *)
                    echo "VVSTUB($sym)"
                    ;;
            esac
        done < "$OUT/$base.syms"
    } > "$OUT/$base.c"
done

echo
echo "== compiling"
for lib in libcudart.so.12 libcublas.so.12 libcublasLt.so.12 libcudnn.so.8 libcufft.so.11; do
    base=$(echo "$lib" | sed 's/\.so\..*//')
    extra=""
    [ "$base" = libcudart ] && extra="src/cudastub.c"

    # The real CUDA libraries version their symbols, and the provider's
    # references carry those versions: `cudaMalloc@libcudart.so.12`.  A stand-in
    # without a matching version node does not merely fail to satisfy them - it
    # trips an assertion inside ld.so.  So define a node with the same name and
    # put everything in it.
    printf '%s {\n  global: *;\n};\n' "$lib" > "$OUT/$base.map"

    gcc -O1 -fPIC -shared -Isrc -o "$OUT/$lib" "$OUT/$base.c" $extra \
        -Wl,-soname,"$lib" -Wl,--version-script="$OUT/$base.map"
    ls -l "$OUT/$lib" | awk '{print "   " $9, $5 " bytes"}'
done
echo "done"
