#!/bin/sh
# Builds stand-in libcudart / libcublas / libcublasLt / libcudnn / libcufft.
#
# The experiment these serve: run the *CUDA* build of voicevox_onnxruntime under
# the emulator with no GPU and no CUDA installed, and find out which of ONNX
# Runtime's 2793 registered kernels a real model actually launches.  That number
# is what decides whether "hook the CUDA calls and do the maths natively" is a
# weekend or a year.
#
# Every entry point the provider imports becomes a stub that returns success.
# A handful are real: the allocator hands out host memory, the copies are
# memcpy, and `__cudaRegisterFunction` records each kernel's name so that
# `cudaLaunchKernel` can print the one being launched.  Nothing computes
# anything - the point is the list of names, not the answer.
#
#   sh tools/make_cuda_stubs.sh <dir with libvoicevox_onnxruntime_providers_cuda.so>
#
# Run it on Linux x86-64 (WSL does).  Output goes to guest/cudastub/.
set -e
cd "$(dirname "$0")/.."
SRC=${1:-cuda/voicevox_onnxruntime-linux-x64-cuda-1.17.3/lib}
PROVIDER="$SRC/libvoicevox_onnxruntime_providers_cuda.so"
[ -f "$PROVIDER" ] || { echo "no $PROVIDER"; exit 1; }

OUT=guest/cudastub
mkdir -p "$OUT"

# The optimiser flags.  These stand-ins run *outside* the emulator, on the real
# host, so unlike the guest they may use whatever the host has - and the
# convolutions are 90 % of the shim's time, so it matters.  Measured, one
# utterance, time inside cuDNN (tools/bench_shim.sh):
#
#     -O2                   6.2 s
#     -O3                   7.5 s     <- slower; Eigen unrolls badly here
#     -O3 -mavx2 -mfma      3.8 s
#
# `-march=native` is *not* the answer on a machine with AVX-512: this repo's
# flattened Eigen does not carry src/Core/arch/AVX512, and the build fails
# outright.  AVX2 is the practical ceiling with it.
# Which half of the shim these stand-ins are.
#
#   native  they do the arithmetic themselves, in this process.  This is the
#           build the whole shim was got right with, and it still is the one to
#           debug against: it runs in a second.
#   guest   they run *inside* the emulator and hand the arithmetic to the host
#           through one reserved syscall (src/vvhostcall.h).  Nothing here
#           computes, so nothing here needs Eigen or a C++ compiler - and the
#           code must be SSE2, because the guest is.
MODE=${MODE:-native}
case "$MODE" in
    native)
        RUNTIME_SRC="src/cudastub.c src/cudakernels.c src/cudainfo.c"
        CUDNN_SRC="src/cudnn_real.cpp"
        CUBLAS_SRC="src/cublas_real.cpp"
        ;;
    guest)
        RUNTIME_SRC="src/cudaguest.c src/cudainfo.c"
        CUDNN_SRC="src/cudnnguest.c"
        CUBLAS_SRC="src/cublasguest.c"
        # The guest is SSE2 and has no VEX decoder.  The host flags below would
        # put an AVX `vmovq` in the very first stub the provider calls.
        [ -z "$OPT" ] && OPT="-O2"
        ;;
    *) echo "MODE must be native or guest"; exit 1 ;;
esac
echo "mode $MODE"

if [ -z "$OPT" ]; then
    if grep -q ' avx2 ' /proc/cpuinfo 2>/dev/null; then
        OPT="-O3 -mavx2 -mfma"
    else
        OPT="-O2"
    fi
fi
echo "flags $OPT"

# Everything the provider needs, grouped by the library it expects it from.
nm -D --undefined-only "$PROVIDER" | awk '{print $2}' | grep '@lib' |
    sed 's/@GLIBC[^ ]*//' | sort -u > "$OUT/imports.txt"

for lib in libcudart.so.12 libcublas.so.12 libcublasLt.so.12 libcudnn.so.8 libcufft.so.11; do
    base=$(echo "$lib" | sed 's/\.so\..*//')
    grep "@$lib\$" "$OUT/imports.txt" | sed "s/@$lib\$//" | sort -u > "$OUT/$base.syms"
    n=$(wc -l < "$OUT/$base.syms")
    printf '%-18s %s symbols\n' "$lib" "$n"

    {
        echo "// Generated by tools/make_cuda_stubs.sh - do not edit."
        echo "// Stand-in for $lib: every entry point the CUDA provider imports,"
        echo "// answering success without doing anything."
        echo '#include "cudastub.h"'
        echo
        while read -r sym; do
            case "$sym" in
                # The ones with real behaviour live in cudastub.c.
                cudaMalloc|cudaFree|cudaMemcpy|cudaMemcpyAsync|cudaMemset|\
cudaMemsetAsync|cudaMallocHost|cudaHostAlloc|cudaFreeHost|cudaLaunchKernel|\
cudaGetDeviceCount|cudaGetDevice|cudaSetDevice|cudaGetDeviceProperties_v2|\
cudaDeviceGetAttribute|cudaRuntimeGetVersion|cudaGetErrorString|cudaGetErrorName|\
cudaStreamCreateWithFlags|cudaStreamDestroy|cudaStreamSynchronize|cudaMemGetInfo|\
cudaMemcpy2DAsync|__cudaRegisterFatBinary|__cudaRegisterFatBinaryEnd|\
__cudaRegisterFunction|__cudaRegisterVar|__cudaUnregisterFatBinary|\
__cudaPushCallConfiguration|__cudaPopCallConfiguration|\
cudnnCreateTensorDescriptor|cudnnDestroyTensorDescriptor|\
cudnnSetTensorNdDescriptor|cudnnSetTensor4dDescriptor|\
cudnnCreateFilterDescriptor|cudnnDestroyFilterDescriptor|\
cudnnSetFilterNdDescriptor|cudnnCreateConvolutionDescriptor|\
cudnnDestroyConvolutionDescriptor|cudnnSetConvolutionNdDescriptor|\
cudnnSetConvolutionGroupCount|cudnnGetConvolutionForwardWorkspaceSize|\
cudnnGetConvolutionBackwardDataWorkspaceSize|\
cudnnFindConvolutionForwardAlgorithmEx|\
cudnnFindConvolutionBackwardDataAlgorithmEx|\
cudnnAddTensor|cudnnConvolutionForward|cudnnConvolutionBackwardData|cublasCreate_v2|cublasDestroy_v2|cublasSetStream_v2|cublasGetStream_v2|cublasSetMathMode|cublasGetMathMode|cublasSetPointerMode_v2|cublasSgemm_v2|cublasSgemmStridedBatched|cublasSgeam)
                    ;;
                *)
                    echo "VVSTUB($sym)"
                    ;;
            esac
        done < "$OUT/$base.syms"
    } > "$OUT/$base.c"
done

echo
echo "== compiling"
for lib in libcudart.so.12 libcublas.so.12 libcublasLt.so.12 libcudnn.so.8 libcufft.so.11; do
    base=$(echo "$lib" | sed 's/\.so\..*//')
    extra=""
    cc="${CC:-gcc} $OPT"
    [ "$base" = libcudart ] && extra="$RUNTIME_SRC"
    if [ "$base" = libcublas ]; then
        extra="$CUBLAS_SRC"
        [ "$MODE" = native ] && cc="${CXX:-$HOME/gpp/bin/g++} $OPT -Ithird_party/eigen_flat"
    fi
    if [ "$base" = libcudnn ]; then
        # Natively the convolutions are here and they use Eigen, so this one
        # needs a C++ compiler; tools/get_gpp_nosudo.sh provides one where apt
        # cannot.  In guest mode there is nothing to compile but trampolines.
        extra="$CUDNN_SRC"
        [ "$MODE" = native ] && cc="${CXX:-$HOME/gpp/bin/g++} $OPT -Ithird_party/eigen_flat"
    fi

    # The real CUDA libraries version their symbols, and the provider's
    # references carry those versions: `cudaMalloc@libcudart.so.12`.  A stand-in
    # without a matching version node does not merely fail to satisfy them - it
    # trips an assertion inside ld.so.  So define a node with the same name and
    # put everything in it.
    printf '%s {\n  global: *;\n};\n' "$lib" > "$OUT/$base.map"

    $cc -fPIC -shared -Isrc -o "$OUT/$lib" "$OUT/$base.c" $extra \
        -Wl,-soname,"$lib" -Wl,--version-script="$OUT/$base.map"
    ls -l "$OUT/$lib" | awk '{print "   " $9, $5 " bytes"}'
done
echo "done"
