#!/bin/sh
# Rewrite the generated ~/gpp/bin/g++ wrapper without -x c++, then re-probe.
# tools/get_gpp_nosudo.sh emits this now; existing installs need rewriting.
PREFIX=$HOME/gpp
GCCDIR=$PREFIX/root/usr/lib/gcc/x86_64-linux-gnu/11
[ -d "$GCCDIR" ] || { echo "no unpacked backend at $GCCDIR"; exit 1; }

cat > "$PREFIX/bin/g++" <<EOF
#!/bin/sh
# Generated by tools/get_gpp_nosudo.sh.  The system gcc, told where the
# unpacked C++ backend and headers live.
#
# No -x c++ here, deliberately.  It looks harmless - gcc picks C++ for a .cpp
# by extension anyway - but -x applies to *every* input that follows it,
# including object files, and gcc then reads an ELF as though it were source
# and reports a stray \\177 on line 1.
exec gcc \\
    -B "$GCCDIR" \\
    -isystem "$PREFIX/root/usr/include/c++/11" \\
    -isystem "$PREFIX/root/usr/include/x86_64-linux-gnu/c++/11" \\
    -isystem "$PREFIX/root/usr/include/c++/11/backward" \\
    "\$@" -lstdc++ -lm
EOF
chmod +x "$PREFIX/bin/g++"
echo "== rewritten"
cat "$PREFIX/bin/g++"
echo "== probe"
sh "$(dirname "$0")/wslprobe.sh"
